Update shell

diff --git a/module/shell b/module/shell
--- a/module/shell
+++ b/module/shell
@@ -1,4 +1,6 @@
 #!/bin/bash
+
+### Usage
 function usage() {
 cat << EOF
 Usage: $0 [required params] [optional params]
@@ -14,6 +16,7 @@ exit 1
 ns=""
 tbl=""
 
+### getopts get short options
 while getopts "n:t:h" opt; do
     case $opt in
         n) ns="$OPTARG" ;;
@@ -22,6 +25,63 @@ while getopts "n:t:h" opt; do
     esac
 done
 
+#处理剩余的参数
+echo "Remaining arguments: ${@:$OPTIND}"
+
+### getopt get short or long options
+# -o或--options选项后面接可接受的短选项，如ab:c::，表示可接受的短选项为-a -b -c，其中-a选项不接参数，-b选项后必须接参数，-c选项的参数为可选的
+# -l或--long选项后面接可接受的长选项，用逗号分开，冒号的意义同短选项。
+# -n选项后接选项解析错误时提示的脚本名字
+ARGS=`getopt -o ab:c:: --long along,blong:,clong:: -n 'example.sh' -- "$@"`
+if [ $? != 0 ]; then
+    echo "Terminating..."
+    exit 1
+fi
+
+#echo $ARGS
+#将规范化后的命令行参数分配至位置参数（$1,$2,...)
+eval set -- "${ARGS}"
+
+while true
+do
+    case "$1" in
+        -a|--along) 
+            echo "Option a";
+            shift
+            ;;
+        -b|--blong)
+            echo "Option b, argument $2";
+            shift 2
+            ;;
+        -c|--clong)
+            case "$2" in
+                "")
+                    echo "Option c, no argument";
+                    shift 2  
+                    ;;
+                *)
+                    echo "Option c, argument $2";
+                    shift 2;
+                    ;;
+            esac
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "Internal error!"
+            exit 1
+            ;;
+    esac
+done
+
+#处理剩余的参数
+echo "Remaining arguments: $@"
+
+
+
+### check options
 [[ -z $ns ]] || [[ -z $tbl ]] && usage
 
 # > false && echo foo || echo bar
